import { describe, expect, it } from "vitest";
import * as publicApi from "../../src/index";

describe("public root API", () => {
  it("keeps an exact runtime export inventory", () => {
    expect(Object.keys(publicApi).sort()).toEqual([
      "FEMGX_FORMAT_VERSION",
      "FIELD_COMPONENT_COUNT",
      "FaceSelectionError",
      "GeometryValidationError",
      "HEX20_SHAPE",
      "HEX8_SHAPE",
      "HeterogeneousElementError",
      "IoError",
      "LINE3_SHAPE",
      "LINE_SHAPE",
      "POINT_SHAPE",
      "PolygonGeometryError",
      "QUAD_SHAPE",
      "TENSOR_COMPONENT",
      "TET10_SHAPE",
      "TET4_SHAPE",
      "TRIANGLE_SHAPE",
      "VtkWriteError",
      "WebGpuPickReadbackError",
      "WebGpuUnsupportedError",
      "boundaryFaceRefs",
      "canvasCssToRenderPixel",
      "classifyFaces",
      "clearSelection",
      "clientToCanvasCss",
      "createCamera",
      "createElement",
      "createElementModel",
      "createElementModelFromFemModel",
      "createFemViewport",
      "createInteractionState",
      "createModelBuilder",
      "createPart",
      "createResultField",
      "createScalarColorMap",
      "createScene",
      "createSceneRuntime",
      "deformGeometry",
      "deformPositions",
      "edgesOf",
      "emphasizedBodyRefs",
      "emphasizedElementRefs",
      "emphasizedFaceRefs",
      "emphasizedNodeRefs",
      "facesOf",
      "facesOfElement",
      "finiteRange",
      "fitCamera",
      "heterogeneousElementParts",
      "identity",
      "installBoxSelection",
      "installCameraControls",
      "instanceToTarget",
      "isBodyEmphasized",
      "isBodyVisible",
      "isFaceEmphasized",
      "isNodeEmphasized",
      "magnitude",
      "magnitudeField",
      "magnitudes",
      "mapScalar",
      "maxPrincipalField",
      "multiply",
      "nodalDisplacements",
      "orbitCamera",
      "panCamera",
      "parseVtk",
      "polygonGeometry",
      "polygonPart",
      "principalValues",
      "principals",
      "projectPoint",
      "projectPolygon",
      "projectionMatrix",
      "queryWebGpuSupport",
      "requestWebGpuAdapter",
      "requestWebGpuDevice",
      "resizeCamera",
      "resolveBodyStyle",
      "resolveElementStyle",
      "resolveFaceStyle",
      "resolveInstanceStyle",
      "resolveNodeStyle",
      "resolvePick",
      "resolvePickTarget",
      "rotationZ",
      "scalarAt",
      "scalarRange",
      "scale",
      "setBodyHighlighted",
      "setBodyOverride",
      "setBodySelected",
      "setBodyVisible",
      "setElementHighlighted",
      "setElementOverride",
      "setElementSelected",
      "setFaceHighlighted",
      "setFaceSelected",
      "setHoveredBody",
      "setHoveredElement",
      "setHoveredFace",
      "setHoveredInstance",
      "setHoveredNode",
      "setInstanceHighlighted",
      "setInstanceOverride",
      "setInstanceSelected",
      "setNodeHighlighted",
      "setNodeSelected",
      "setPartHighlighted",
      "setPartOverride",
      "setPartSelected",
      "setProjection",
      "setTargetHighlighted",
      "setTargetSelected",
      "setTargetsHighlighted",
      "tensorAt",
      "tensorMagnitude",
      "topologyFor",
      "transformPoint",
      "translation",
      "uniqueEdges",
      "unprojectPoint",
      "unsupportedMessage",
      "validateModel",
      "vectorAt",
      "viewMatrix",
      "viewProjectionMatrix",
      "vonMises",
      "vonMisesField",
      "vonMisesValues",
      "writeVtk",
      "zoomCamera",
      "zoomCameraAtPoint",
    ]);
  });

  it("does not expose renderer/runtime implementation helpers", () => {
    expect(publicApi).not.toHaveProperty("createWebGpuRenderer");
    expect(publicApi).not.toHaveProperty("changedInstanceSlots");
    expect(publicApi).not.toHaveProperty("faceTriangles");
  });

  it("exposes the canonical scene, viewport, and results entry points", () => {
    expect(publicApi.createScene).toBeTypeOf("function");
    expect(publicApi.createFemViewport).toBeTypeOf("function");
    expect(publicApi.createResultField).toBeTypeOf("function");
    expect(publicApi.polygonGeometry).toBeTypeOf("function");
    expect(publicApi.polygonPart).toBeTypeOf("function");
    expect(publicApi.PolygonGeometryError).toBeTypeOf("function");
    expect(publicApi.boundaryFaceRefs).toBeTypeOf("function");
    expect(publicApi.FaceSelectionError).toBeTypeOf("function");
    expect(publicApi.heterogeneousElementParts).toBeTypeOf("function");
    expect(publicApi.HeterogeneousElementError).toBeTypeOf("function");
    expect(publicApi.createElementModelFromFemModel).toBeTypeOf("function");
  });

  it("exposes validated part-body metadata helpers", () => {
    expect(publicApi.GeometryValidationError).toBeTypeOf("function");
    expect(publicApi.createPart).toBeTypeOf("function");
  });

  it("exposes body interaction helpers through the root API", () => {
    expect(publicApi.setBodyVisible).toBeTypeOf("function");
    expect(publicApi.setBodyOverride).toBeTypeOf("function");
    expect(publicApi.setBodyHighlighted).toBeTypeOf("function");
    expect(publicApi.setBodySelected).toBeTypeOf("function");
    expect(publicApi.setHoveredBody).toBeTypeOf("function");
  });
});
