import { describe, expect, it } from "vitest";
import * as publicApi from "../../src/index";

describe("public root API", () => {
  it("keeps an exact runtime export inventory", () => {
    expect(Object.keys(publicApi).sort()).toEqual([
      "ElementModelEditError",
      "ElementModelValidationError",
      "FEMGX_FORMAT_VERSION",
      "FIELD_COMPONENT_COUNT",
      "FaceSelectionError",
      "GeometryValidationError",
      "HEX20_SHAPE",
      "HEX8_SHAPE",
      "HeterogeneousElementError",
      "IoError",
      "LINE3_SHAPE",
      "LINE_SHAPE",
      "POINT_SHAPE",
      "PYRAMID5_SHAPE",
      "PolygonGeometryError",
      "QUAD8_SHAPE",
      "QUAD_SHAPE",
      "TET10_SHAPE",
      "TET4_SHAPE",
      "TRI6_SHAPE",
      "TRIANGLE_SHAPE",
      "VtkWriteError",
      "WEDGE6_SHAPE",
      "WebGpuPickReadbackError",
      "WebGpuUnsupportedError",
      "bodyOverride",
      "boundaryFaceRefs",
      "boxSelectionFrustum",
      "canvasCssToRenderPixel",
      "classifyFaces",
      "clearSelection",
      "clientToCanvasCss",
      "createCamera",
      "createElement",
      "createElementModel",
      "createElementModelFromFemModel",
      "createFemViewport",
      "createInteractionState",
      "createModelBuilder",
      "createPart",
      "createResultField",
      "createResultFieldFromModelResult",
      "createScalarColorMap",
      "createScene",
      "createSceneRuntime",
      "deformGeometry",
      "deformPositions",
      "edgesOf",
      "editElementModel",
      "emphasizedBodyRefs",
      "emphasizedEdgeRefs",
      "emphasizedElementBlockRefs",
      "emphasizedElementRefs",
      "emphasizedFaceRefs",
      "emphasizedNodeRefs",
      "facesOf",
      "facesOfElement",
      "finiteRange",
      "fitCamera",
      "heterogeneousElementParts",
      "hoveredTarget",
      "identity",
      "importGlb",
      "installBoxSelection",
      "installCameraControls",
      "interactionTargetFromHit",
      "isBodyEmphasized",
      "isBodyVisible",
      "isEdgeEmphasized",
      "isElementBlockEmphasized",
      "isElementBlockVisible",
      "isElementVisible",
      "isFaceEmphasized",
      "isHoveredTarget",
      "isNodeEmphasized",
      "isTargetHighlighted",
      "isTargetSelected",
      "mapScalar",
      "multiply",
      "nodalDisplacements",
      "orbitCamera",
      "panCamera",
      "parseVtk",
      "polygonGeometry",
      "polygonPart",
      "projectPoint",
      "projectPolygon",
      "projectionMatrix",
      "queryWebGpuSupport",
      "requestWebGpuAdapter",
      "requestWebGpuDevice",
      "resizeCamera",
      "resolveBodyStyle",
      "resolveEdgeStyle",
      "resolveElementBlockStyle",
      "resolveElementStyle",
      "resolveFaceStyle",
      "resolveInstanceStyle",
      "resolveNodeStyle",
      "rotationZ",
      "scalarAt",
      "scalarRange",
      "scale",
      "selectedTargets",
      "setBodyOverride",
      "setBodyVisible",
      "setElementBlockHighlighted",
      "setElementBlockOverride",
      "setElementBlockSelected",
      "setElementBlockVisible",
      "setElementOverride",
      "setElementVisible",
      "setInstanceOverride",
      "setPartOverride",
      "setProjection",
      "setTargetHighlighted",
      "setTargetHovered",
      "setTargetSelected",
      "setTargetsHighlighted",
      "setTargetsSelected",
      "topologyFor",
      "transformPoint",
      "translation",
      "uniqueEdges",
      "unprojectPoint",
      "unsupportedMessage",
      "validateModel",
      "vectorAt",
      "viewMatrix",
      "viewProjectionMatrix",
      "writeVtk",
      "zoomCamera",
      "zoomCameraAtPoint",
    ]);
  });

  it("does not expose renderer/runtime implementation helpers", () => {
    expect(publicApi).not.toHaveProperty("createWebGpuRenderer");
    expect(publicApi).not.toHaveProperty("changedInstanceSlots");
    expect(publicApi).not.toHaveProperty("faceTriangles");
  });

  it("exposes the canonical scene, viewport, and results entry points", () => {
    expect(publicApi.createScene).toBeTypeOf("function");
    expect(publicApi.createFemViewport).toBeTypeOf("function");
    expect(publicApi.createResultField).toBeTypeOf("function");
    expect(publicApi.createResultFieldFromModelResult).toBeTypeOf("function");
    expect(publicApi.polygonGeometry).toBeTypeOf("function");
    expect(publicApi.polygonPart).toBeTypeOf("function");
    expect(publicApi.PolygonGeometryError).toBeTypeOf("function");
    expect(publicApi.boundaryFaceRefs).toBeTypeOf("function");
    expect(publicApi.FaceSelectionError).toBeTypeOf("function");
    expect(publicApi.heterogeneousElementParts).toBeTypeOf("function");
    expect(publicApi.HeterogeneousElementError).toBeTypeOf("function");
    expect(publicApi.createElementModelFromFemModel).toBeTypeOf("function");
    expect(publicApi.importGlb).toBeTypeOf("function");
    expect(publicApi.editElementModel).toBeTypeOf("function");
    expect(publicApi.ElementModelEditError).toBeTypeOf("function");
  });

  it("exposes validated part-body metadata helpers", () => {
    expect(publicApi.GeometryValidationError).toBeTypeOf("function");
    expect(publicApi.createPart).toBeTypeOf("function");
  });

  it("exposes body visibility and target interaction helpers through the root API", () => {
    expect(publicApi.setBodyVisible).toBeTypeOf("function");
    expect(publicApi.setBodyOverride).toBeTypeOf("function");
    expect(publicApi.setTargetSelected).toBeTypeOf("function");
    expect(publicApi.setTargetHovered).toBeTypeOf("function");
  });
});
