import { ElementShape } from "../../../src/elements/shapes";

import type { GoldenElementConvention } from "./types";

export const surfaceConventions: readonly GoldenElementConvention[] = [
  {
    name: "triangle",
    shape: ElementShape.Triangle,
    nodeCount: 3,
    corners: [0, 1, 2],
    edges: [
      [0, 1],
      [1, 2],
      [2, 0],
    ],
    edgeNodes: [],
    reference: [
      [0, 0, 0],
      [1, 0, 0],
      [0, 1, 0],
    ],
    faces: [[0, 1, 2]],
    edgeSequences: [
      [0, 1],
      [1, 2],
      [2, 0],
    ],
    bounds: { minX: 0, minY: 0, minZ: 0, maxX: 1, maxY: 1, maxZ: 0 },
    volume: 0,
  },
  {
    name: "tri6",
    shape: ElementShape.Tri6,
    nodeCount: 6,
    corners: [0, 1, 2],
    edges: [
      [0, 1],
      [1, 2],
      [2, 0],
    ],
    edgeNodes: [3, 4, 5],
    reference: [
      [0, 0, 0],
      [1, 0, 0],
      [0, 1, 0],
      [0.5, 0, 0],
      [0.5, 0.5, 0],
      [0, 0.5, 0],
    ],
    faces: [[0, 3, 1, 4, 2, 5]],
    edgeSequences: [
      [0, 3, 1],
      [1, 4, 2],
      [2, 5, 0],
    ],
    bounds: { minX: 0, minY: 0, minZ: 0, maxX: 1, maxY: 1, maxZ: 0 },
    volume: 0,
  },
  {
    name: "quad",
    shape: ElementShape.Quad,
    nodeCount: 4,
    corners: [0, 1, 2, 3],
    edges: [
      [0, 1],
      [1, 2],
      [2, 3],
      [3, 0],
    ],
    edgeNodes: [],
    reference: [
      [0, 0, 0],
      [1, 0, 0],
      [1, 1, 0],
      [0, 1, 0],
    ],
    faces: [[0, 1, 2, 3]],
    edgeSequences: [
      [0, 1],
      [1, 2],
      [2, 3],
      [3, 0],
    ],
    bounds: { minX: 0, minY: 0, minZ: 0, maxX: 1, maxY: 1, maxZ: 0 },
    volume: 0,
  },
  {
    name: "quad8",
    shape: ElementShape.Quad8,
    nodeCount: 8,
    corners: [0, 1, 2, 3],
    edges: [
      [0, 1],
      [1, 2],
      [2, 3],
      [3, 0],
    ],
    edgeNodes: [4, 5, 6, 7],
    reference: [
      [0, 0, 0],
      [1, 0, 0],
      [1, 1, 0],
      [0, 1, 0],
      [0.5, 0, 0],
      [1, 0.5, 0],
      [0.5, 1, 0],
      [0, 0.5, 0],
    ],
    faces: [[0, 4, 1, 5, 2, 6, 3, 7]],
    edgeSequences: [
      [0, 4, 1],
      [1, 5, 2],
      [2, 6, 3],
      [3, 7, 0],
    ],
    bounds: { minX: 0, minY: 0, minZ: 0, maxX: 1, maxY: 1, maxZ: 0 },
    volume: 0,
  },
];
